### ISSUE TITLE
Despite errors, `jpm test` prints `All tests passed.` and has error code 0

### ISSUE THREAD

**Issue by saikyun** [janet-lang/jpm#47]
Using either:
- Windows 11, commit ce14c833e6ea69f1515c59a1f3898dba419f0f4d, using Native Tools Command Prompt for VS 2019
- Github CI windows-latest

`jpm test` seems to always return 0.

Example:
```
git clone https://github.com/saikyun/jpm-wrong-error-code
cd jpm-wrong-error-code
jpm test
running test/error.janet ...
error: wat
  in _thunk [test/error.janet] (tailcall) on line 1, column 1
running test/exit.janet ...
All tests passed.
```

The tests are running `(error "wat")` and `(os/exit 1)`.

**Comment by sogaiu** [comment]
I was able to reproduce this in a Windows environment using jpm at the [latest commit](https://github.com/janet-lang/jpm/commit/ce14c833e6ea69f1515c59a1f3898dba419f0f4d) and janet at the [latest commit](https://github.com/janet-lang/janet/commit/9d0da74347db1b5e601e5977ccd91391ecca0a7f).

On a side note, behavior was as expected under a Linux environment -- i.e.
```
$ jpm test
running test/error.janet ...
error: wat
  in _thunk [test/error.janet] (tailcall) on line 1, column 1
non-zero exit code in test/error.janet: 1
running test/exit.janet ...
non-zero exit code in test/exit.janet: 1
Failing test scripts: 2
```

**Comment by bakpakin** [comment]
Looks like this was an error in Janet, has been fixed on master: https://github.com/janet-lang/janet/commit/427f7c362e19117c6ac91b9fe2419019c0adbeb3

We were using the wrong member of a structure to get the return value of the process.

**Comment by sogaiu** [comment]
I still get similar errors.  May be I didn't update appropriately.

Perhaps @saikyun wouldn't mind trying?

**Comment by bakpakin** [comment]
I can confirm the update works - tested with latest master and spork with a fake bug introduced.

**Comment by sogaiu** [comment]
Confirmed it's working here.  I think I misinterpreted the output before.  Sorry about that.
